Repository pioneers/runtime, pull requests merged in 2020-08, with the labels that each got.

#102 Device Handler CLI, Client, and Tests
  dev_handler/dev_handler.c
  dev_handler/message.c
  dev_handler/message.h
  lowcar/devices/Device/Device.cpp
  lowcar/devices/Device/Device.h
  lowcar/devices/DummyDevice/DummyDevice.cpp
  lowcar/devices/DummyDevice/DummyDevice.h
  lowcar/devices/RFID/RFID.cpp
  lowcar/devices/RFID/RFID.h
  run.sh
  runtime_util/runtime_util.c
  runtime_util/runtime_util.h
  shm_wrapper/shm_wrapper.c
  shm_wrapper/static_dev.c
  tests/Makefile
  tests/cli/dev_handler_cli.c
  tests/client/dev_handler_client.c
  tests/client/dev_handler_client.h
  tests/client/virtual_devices/foreign_dev.c
  tests/client/virtual_devices/general_dev.c
  tests/client/virtual_devices/simple_dev.c
  tests/client/virtual_devices/time_dev.c
  tests/client/virtual_devices/unresponsive_dev.c
  tests/client/virtual_devices/unstable_dev.c
  tests/client/virtual_devices/virtual_device_util.c
  tests/client/virtual_devices/virtual_device_util.h
  tests/integration/tc_68_10.c
  tests/integration/tc_68_11.c
  tests/integration/tc_68_12.c
  tests/integration/tc_68_13.c
  tests/integration/tc_68_14.c
  tests/integration/tc_68_15.c
  tests/integration/tc_68_5.c
  tests/integration/tc_68_6.c
  tests/integration/tc_68_7.c
  tests/integration/tc_68_8.c
  tests/integration/tc_68_9.c
  tests/student_code/runtime_latency.py
  tests/student_code/sanity_write.py
  tests/test.c
  tests/test.h
Labels: enhancement, high-priority, testing

#103 [TEST] Changed test.c to use thread, not process. Remove temp file
  test.sh
  tests/test.c
  tests/test.h
Labels: enhancement, testing

#104 [DOCS] Renamed images -> docs folder, added diagrams from docs_issue_68
  dev_handler/dev_handler.c
  docs/CLI-Client-Test-Relationship.graffle
  docs/CLI-Client-Test-Relationship.png
  docs/Client-Lifetime.graffle
  docs/Client-Lifetime.png
  docs/Dump-To-Dev-Null.graffle
  docs/Dump-To-Dev-Null.png
  docs/Log-FIFO-State-Machine.graffle
  docs/Log-FIFO-State-Machine.png
  docs/Net-Client-Output-Suppression.graffle
  docs/Net-Client-Output-Suppression.png
  docs/Runtime-Black-Box.graffle
  docs/Runtime-Black-Box.png
  docs/Runtime-Diagram.graffle
  docs/Runtime-Diagram.png
  docs/Shm-Client.graffle
  docs/Shm-Client.png
  docs/Test-Output-Redirect-Logic.graffle
  docs/Test-Output-Redirect-Logic.png
  docs/style_guide.c
  images/Runtime-Diagram.graffle
  images/Runtime-Diagram.png
Labels: documentation
