Repository pioneers/runtime, pull requests merged in 2020-10, with the labels that each got.

#122 [MISC] Gamepad error check
  net_handler/udp_conn.c
  tests/integration/tc_71_17.c
  tests/integration/tc_71_18.c
  tests/integration/tc_71_4.c
Labels: bug

#124 [DOCS] Added Executor flow chart
  docs/Executor Flow Chart.png
Labels: documentation

#120 [MISC] Keyboard Interface and SoundDevice
  docker-compose.yml
  executor/sound_device.py
  runtime_util/runtime_util.c
  tests/Makefile
  tests/cli/dev_handler_cli.c
  tests/cli/keyboard_inputs.py
  tests/cli/keyboard_interface.c
  tests/client/net_handler_client.c
  tests/client/virtual_devices/sound.py
  tests/client/virtual_devices/sound_dev.c
  tests/client/virtual_devices/virtual_device_util.c
  tests/client/virtual_devices/virtual_device_util.h
  tests/integration/tc_71_17.c
  tests/integration/tc_71_4.c
Labels: enhancement
