Repository pioneers/runtime, pull requests merged in 2021-01, with the labels that each got.

#143 [DEV_HANDLER] Fixes runtime crash when running as systemd
  dev_handler/dev_handler.c
Labels: bug, high-priority

#146 [SYSTEMD] Implementing circular restarting of Runtime
  scripts/run.sh
  systemd/dev_handler.service
  systemd/executor.service
  systemd/net_handler.service
  systemd/shm_stop.service
Labels: bug

#158 [NET_HANDLER] Removed protobuf_tests; updated README and Makefile
  README.md
  net_handler/Makefile
  net_handler/README.md
  net_handler/protobuf_tests/devdata_in.c
  net_handler/protobuf_tests/devdata_out.c
  net_handler/protobuf_tests/gpstate_in.c
  net_handler/protobuf_tests/gpstate_out.c
  net_handler/protobuf_tests/log_in.c
  net_handler/protobuf_tests/log_out.c
  net_handler/protobuf_tests/runmode_in.c
  net_handler/protobuf_tests/runmode_out.c
  net_handler/protobuf_tests/tcp_pb_client.c
  net_handler/protobuf_tests/tcp_pb_server.c
Labels: code-cleanup, documentation

#154 Shared Memory UI
  README.md
  tests/Makefile
  tests/cli/shm_cli.c
  tests/cli/shm_ui.c
Labels: enhancement, testing

#157 Added a new Keyboard class to the Student API
  docker/README.md
  executor/Makefile
  executor/executor.c
  executor/runtime.pxd
  executor/studentapi.pyx
  logger/logger.c
  net_handler/Makefile
  net_handler/net_util.h
  net_handler/pbc_gen/gamepad.pb-c.c
  net_handler/pbc_gen/gamepad.pb-c.h
  net_handler/pbc_gen/input.pb-c.c
  net_handler/pbc_gen/input.pb-c.h
  net_handler/protos/gamepad.proto
  net_handler/protos/input.proto
  net_handler/tcp_conn.c
  net_handler/udp_conn.c
  runtime
  runtime_util/runtime_util.c
  runtime_util/runtime_util.h
  scripts/stop.sh
  shm_wrapper/Makefile
  shm_wrapper/shm_start.c
  shm_wrapper/shm_stop.c
  shm_wrapper/shm_wrapper.c
  shm_wrapper/shm_wrapper.h
  shm_wrapper/shm_wrapper_test1.c
  shm_wrapper/shm_wrapper_test2.c
  tests/Makefile
  tests/cli/keyboard_interface.c
  tests/cli/net_handler_cli.c
  tests/cli/shm_ui.c
  tests/client/executor_client.h
  tests/client/net_handler_client.c
  tests/client/net_handler_client.h
  tests/client/shm_client.c
  tests/client/virtual_devices/ForeignTestDevice.c
  tests/client/virtual_devices/GeneralTestDevice.c
  tests/client/virtual_devices/SimpleTestDevice.c
  tests/client/virtual_devices/SoundDevice.c
  tests/client/virtual_devices/TimeTestDevice.c
  tests/client/virtual_devices/UnresponsiveTestDevice.c
  tests/client/virtual_devices/UnstableTestDevice.c
  tests/integration/tc_150_1.c
  tests/integration/tc_71_10.c
  tests/integration/tc_71_17.c
  tests/integration/tc_71_18.c
  tests/integration/tc_71_4.c
  tests/logger.config
  tests/student_code/keyboard_input.py
  tests/test.c
  tests/test.h
Labels: enhancement, high-priority

#168 [MISC] Display help for runtime script
  runtime
Labels: documentation

#169 [SYSTEMD] Small systemd changes
  shm_wrapper/Makefile
  shm_wrapper/README.md
  shm_wrapper/shm_wrapper_test1.c
  shm_wrapper/shm_wrapper_test2.c
  systemd/README.md
  systemd/test/script1.py
  systemd/test/script2.py
  systemd/test/script3.py
  systemd/test/script4.py
  systemd/test/script5.py
  systemd/test/test1.service
  systemd/test/test2.service
  systemd/test/test3.service
  systemd/test/test4.service
  systemd/test/test5.service
Labels: code-cleanup

#167 [EXECUTOR] Fix regex for subscription parsing in student code
  executor/runtime.pxd
  executor/studentapi.pyx
  executor/studentcode.py
  shm_wrapper/shm_wrapper.c
  shm_wrapper/shm_wrapper.h
  tests/client/net_handler_client.c
  tests/client/virtual_devices/virtual_device_util.c
  tests/integration/tc_150_1.c
  tests/integration/tc_159_1.c
  tests/integration/tc_71_1.c
  tests/student_code/sound_device.py
  tests/student_code/subscriptions.py
  tests/test.c
  tests/test.h
Labels: bug

#160 [TEST] Fixed latency bug
  tests/integration/tc_71_10.c
  tests/test.c
  tests/test.h
Labels: bug

#173 [NET_HANDLER] Fix memory leak in send_log_msg()
  net_handler/tcp_conn.c
Labels: bug

#172 [SHM] Add keyboard window to the dashboard
  shm_wrapper/shm_wrapper.c
  shm_wrapper/shm_wrapper.h
  tests/cli/keyboard_inputs.py
  tests/cli/keyboard_interface.c
  tests/cli/shm_ui.c
  tests/client/net_handler_client.c
  tests/client/shm_client.c
  tests/client/shm_client.h
Labels: enhancement
