Repository pioneers/runtime, pull requests merged in 2021-09, with the labels that each got.

#227 [NET_HANDLER] Merge UDP functionality into TCP connection
  .travis.yml
  net_handler/Makefile
  net_handler/README.md
  net_handler/connection.c
  net_handler/connection.h
  net_handler/message.c
  net_handler/message.h
  net_handler/net_handler.c
  net_handler/net_util.h
  net_handler/tcp_conn.c
  net_handler/udp_conn.c
  net_handler/udp_conn.h
  net_handler/udp_tcp_converter.c
  net_handler/udp_tcp_converter_test.c
  runtime
  runtime_util/runtime_util.c
  scripts/test.sh
  systemd/converter.service
  systemd/ngrok.yml
  systemd/ngrok_displayer.py
  tests/Makefile
  tests/README.md
  tests/cli/net_handler_cli.c
  tests/client/net_handler_client.c
  tests/client/net_handler_client.h
  tests/integration/tc_150_1.c
  tests/integration/tc_71_17.c
  tests/integration/tc_71_4.c
  tests/performance/tc_71_10.c
  tests/test.c
  tests/test.h
Labels: code-cleanup

#234 [DEV_HANDLER][NET_HANDLER][SHM] Remove device subscriptions
  .gitignore
  dev_handler/README.md
  dev_handler/dev_handler.c
  dev_handler/message.c
  dev_handler/message.h
  executor/executor.c
  executor/runtime.pxd
  executor/studentapi.pyx
  executor/test_studentapi.py
  lowcar/devices/Device/Device.cpp
  lowcar/devices/Device/Device.h
  lowcar/devices/Device/defs.h
  net_handler/message.c
  runtime_util/runtime_util.c
  runtime_util/runtime_util.h
  shm_wrapper/shm_start.c
  shm_wrapper/shm_stop.c
  shm_wrapper/shm_wrapper.c
  shm_wrapper/shm_wrapper.h
  tests/cli/net_handler_cli.c
  tests/cli/shm_ui.c
  tests/client/net_handler_client.c
  tests/client/net_handler_client.h
  tests/client/virtual_devices/virtual_device_util.c
  tests/client/virtual_devices/virtual_device_util.h
  tests/integration/tc_159_1.c
  tests/integration/tc_71_18.c
  tests/integration/tc_71_3.c
  tests/student_code/subscriptions.py
  tests/test.c
  tests/test.h
Labels: code-cleanup

#237 [SYSTEMD][BUILD] New set_time.service and Travis builds cli
  docker/Dockerfile
  systemd/set_time.service
  systemd/set_time.sh
Labels: enhancement

#245 [LOWCAR][DEV_HANDLER] Remove LED test in KoalaBear
  dev_handler/Makefile
  dev_handler/message.h
  lowcar/devices/Device/Device.cpp
  lowcar/devices/Device/Device.h
  lowcar/devices/KoalaBear/KoalaBear.cpp
Labels: bug
